spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    properties:
        hibernate:
          format_sql: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    post: 587
    protocol: smtps
    username: arsenminnegulov@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
        springframework:
          security: DEBUG
          web: DEBUG

file:
  storage:
    location: file-storage

email:
  subject: Email address confirmation
  messages: Click on the link to confirm your email address -