spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thoughts
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    properties:
        hibernate:
          format_sql: true
          hbm2ddl:
            auto: validate
    open-in-view: false
  mail:
    host: smtp.gmail.com
    post: 587
    protocol: smtps
    username: arsenminnegulov@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
        springframework:
          security: DEBUG
          web: DEBUG

file:
  storage:
    location: Users/adsima/uploads

email:
  subject: Email address confirmation
  messages: Click on the link to confirm your email address

link:
  verify: http://192.168.0.102/registration/verify-email?token=
